backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: "video"
    label: "Video Post"
    folder: "src/pages/video-post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "video-post"}
      - {label: "Path (must begin with a /)", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Video", name: "video", widget: "string"}
      - {label: "Tags", name: "tags", widget: list }
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "image"
    label: "Image Post"
    folder: "src/pages/image-post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "image-post"}
      - {label: "Path (must begin with a /)", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Big?", name: "big", widget: "boolean"}
      - {label: "Images", name: "images", widget: list, fields: [{label: "Image", name: "image", widget: "image"},{label: "Description", name: "description", required: false}] }
      - {label: "Tags", name: "tags", widget: list }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "text"
    label: "Text Post"
    folder: "src/pages/text-post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "text-post"}
      - {label: "Path (must begin with a /)", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: list }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/site-data.md"
        label: "Site Data"
        name: "site-data"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "site-data"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Summary", name: "summary", widget: "string"}
          - {label: "Profile Image", name: "profile_image", widget: "image"}
          - label: "Tags to show on the front page"
            name: "filterTags"
            widget: list
            fields:
              - label: "Tag"
                name: "key"
              - label: "Description"
                name: "description"
          - label: "Links"
            name: "links"
            widget: list
            fields:
              - label: "Name"
                name: "name"
              - label: "Url"
                name: "url"
          - label: "Software List"
            name: "software_list"
            widget: list
            fields:
              - label: "Name"
                name: "name"